### ISSUE TITLE
Blast Furnace Animation.

### ISSUE THREAD

**Issue by Khikki** [jss2a98aj/Et-Futurum#9]
I noticed a small error with Furnace.

![2021-02-05_02 06 31](https://user-images.githubusercontent.com/35336209/106981283-6e521700-676a-11eb-960a-3c7cc3431aad.png)

**Comment by Roadhog360** [comment]
What mod is that texture from? I can't reproduce this.
![image](https://user-images.githubusercontent.com/11903511/107268160-c52f4900-6a15-11eb-842c-b3edbd28227b.png)

**Comment by Khikki** [comment]
Sure, can take a look: [Modslist.txt](https://github.com/jss2a98aj/Et-Futurum/files/5948046/modslist.txt) or https://pastebin.com/smgK62fd

**Comment by Roadhog360** [comment]
What about the mod the texture is from?

**Comment by DarianLStephens** [comment]
Looks like it might just be Dark Prismarine, but blue?

**Comment by Roadhog360** [comment]
Awaiting response for more info -- added Question tag

**Comment by 062regrahc** [comment]
that's the Sapphire Block texture from Biomes o' Plenty

**Comment by Khikki** [comment]
Oh, I completely forgot about this issues, I'm sorry, but yes with the addition of mods, it is replaced by textures from biomes o plenty. 
![image](https://user-images.githubusercontent.com/35336209/108303711-162a0480-71af-11eb-89c4-6b8b583b6227.png)

**Comment by Roadhog360** [comment]
I recently rewrite the interpolated texture system to be less hacky and I realised this might fix this issue as the new system is more proper.

A discussion recently came up about this in my buddy's Discord server that it's caused by newer versions of OptiFine, typically ones with Shaders. Do you have OptiFine? I realised it doesn't show up in mod lists. If you have OptiFine my newest commit may fix this issue, although I highly encourage you uninstall OptiFine, as it is unreliable in 1.7.10 with Forge

If you have OptiFine I'll let you know when a new snapshot is out. 2.1.0 Snapshot 1 won't have the fix, it's just an older snapshot  I released in a friend's Discord a few days ago I forgot to put here, Snapshot 2 will be what you're looking for.

**Comment by Roadhog360** [comment]
There was no response in 18 days so I'll be closing this issue as I'm certain the new snapshot fixes this.
